# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 000efd931433bd32f74df776500e170b654ba55afc37e2bf273302e3e9bf30c02f587d7889a59d3ca79bfcc152bb1cdabc18112cfebd77f644e9d1d614730612

test:
  secret_key_base: c0523942aaef93f27a1d7f71376ca5aeb138354583534ade2f65570cc68c1c0e81ce63285a791f91489c72fdd362e234e9d893e1a5f0db65d59f7750a82e5b83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
